var MANAGER = {};
	MANAGER.quantity = 1;
	
	var items = {};
	
	var resources = {
		money: 100,
	};
	
	function init(){
	
		keyDownEventsInit();
		
		$("#resources").html("money: <label id='cantidadmoney'>0</label>");
	
		var html = ""
		
	
		var itemPromptName = prompt("Please enter item name, or press cancel to exit the item creator","");
		var itemPromptPrice = prompt("Please enter initial price item by using name:quantity;otherName:otherQuantity","");
		var itemPromptIncrement = prompt("Please enter increment like \" 1.05  \" that will increase the price of the item  ","");
		var itemPromptResource = prompt("Please enter the name of the resource this item will create, it can be other item too; then enter a comma \",\" and then enter the amount of that resource. Press enter, you will be asked to input another resource if you want, to stop this process click cancel","money");
		while(itemPromptName != null){ //this while keeps recording as far as theitem ca build another resource, we have to think about some help here for the user input
			var itemResources = [];
			while (itemPromptResource != null){
				datos = itemPromptResource.split(',');//beside each resource separated in some inputs, also its separated for the quantity with a comma
				
				itemResources.push({resource:datos[0],quantity:datos[1]});
				itemPromptResource = prompt("Please enter the name of the resource this item will create, it can be other item too; then enter a comma \",\" and then enter the amount of that resource. Press enter, you will be asked to input another resource if you want, to stop this process click cancel","money");
			}
			var itemPrices = {}; //for the multiple item prices go here, maybe i have to base it like the resources in a multiple input based, but for now its name:quantity;othername:quantity2;name3:quantity3
			resourceType = itemPromptPrice.split(';');//first split the pair of name:quantity
			
			for (index = 0; index < resourceType.length; ++index) {
				priceResourceQuantity = resourceType[index].split(':');//then splits the name:quantity, to get the name and the quantity, i will use this later
				itemPrices[priceResourceQuantity[0]] = {};
				itemPrices[priceResourceQuantity[0]].quantity = priceResourceQuantity[1];  //i will use an strategy to get the resource and the name later in the buying on the item, i will let the html for later, that it will be hard with this multiprice based
			}
			
			
			items[itemPromptName] = {
				nombre: itemPromptName,
				price: itemPrices,
				increment: itemPromptIncrement,
				resource: itemResources,
				quantity: 0,
				updateHtml : function(){
					$("#"+ this.nombre +"").text(this.nombre+": "+this.quantity);
					//$("#"+ this.nombre +"Price").text(this.price*MANAGER.quantity);   //cancelled as problems with html, better to be aside of this
				}
			}
			html+="<div class='butt' onclick='buyItem(\"" + itemPromptName +"\", "+ MANAGER.quantity +")'><label id=" + itemPromptName + ">"+ itemPromptName +"</label><br/><label id='" + itemPromptName + "Price'>"+ itemPromptPrice +"</label><br/><label>"+ JSON.stringify(itemResources) +"</label></div><br/>"
		
			
		
			itemPromptName = prompt("Please enter item name, or press cancel to exit the item creator","");
			itemPromptPrice = prompt("Please enter initial price item","");
			itemPromptIncrement = prompt("Please enter increment like \" 1.05  \" that will increase the price of the item  ","");
			itemPromptResource = prompt("Please enter the name of the resource this item will create, it can be other item too","money");
		}
		$("#items").html(html);
		//runFunctions();
		var cualc = setInterval(function(){ runFunctions()}, 1000);
		//prompt("test",JSON.stringify(items));
	
	}
	
	

	var runFunctions = function(){
	
		produceResources();
		updateItems();
		
	}
	
	function updateItems(){
		for(var propertyName in items) {
			items[propertyName].updateHtml();
		}
	}
	
	function produceResources(){
		
		for(var propertyName in items) { //for each item you have
			var resourcesArray = items[propertyName].resource; //the resources of the array
			for (index = 0; index < resourcesArray.length; ++index) { //for each resource generated by the item
				var resourceName = resourcesArray[index].resource; //get the name of the resource to work by
				var resourceQuantity = resourcesArray[index].quantity; //get the amount of the resource to work by
				
				if(items[resourceName] != null){ //if exist an item of the given resource name, then, add that item quantity based on production
					items[resourceName].quantity += items[propertyName].quantity*resourceQuantity;
				}else{  //if not then search if the resource is already created, if its already created adds to that resource quantity, else,  change that quantity with the amount generated and add the necessary html
					if(resources[resourceName] != null && resources[resourceName]>=0 ){
						resources[resourceName] += items[propertyName].quantity*resourceQuantity;
						$("#cantidad"+resourceName).html(resources[resourceName]);
					}else{
						resources[resourceName] = items[propertyName].quantity*resourceQuantity;
						var resourcesDiv = $("#resources");
						resourcesDiv.html(resourcesDiv.html()+"  -  "+resourceName+": <label id='cantidad"+ resourceName +"'>"+items[propertyName].quantity*resourceQuantity+"</label>");
					}
				}
			}
		}
	}
	
	
	
	function keyDownEventsInit(){
		var eventHandler = {};
		eventHandler.keyAllowed = {};
		

		$(document).keydown(function(e) {
			if (eventHandler.keyAllowed [e.which] === false) return;
			eventHandler.keyAllowed [e.which] = false;
			if(e.which == 17 ){
				MANAGER.quantity*=100;
				updateItems();
				return;
			}
			if(e.which == 16){
				MANAGER.quantity*=10;
				updateItems();
				return;
			}
		});

		$(document).keyup(function(e) { 
		  eventHandler.keyAllowed [e.which] = true;
		  if(e.which == 17 ){
				MANAGER.quantity/=100;
				updateItems();
				return;
			}
			if(e.which == 16){
				MANAGER.quantity/=10;
				updateItems();
				return;
			}
		});

		$(document).focus(function(e) { 
		  eventHandler.keyAllowed = {};
		});
		
	}
	
	var buyItem = function(name){
		quantity = MANAGER.quantity;
		
		for(var propertyName in items[name].price) { //for each resource to buy the item
			if(resources[propertyName] ==null || resources[propertyName] < items[name].price[propertyName].quantity*quantity){ //asks if it exists the necessary resource, and if it have the necessary amount
				console.log("no puedo");
				return;
			}
		}
		
		for(var propertyName in items[name].price) { //another for each to reduce the resources spent into the buying
				resources[propertyName] -= items[name].price[propertyName].quantity*quantity;
				for(i=1;i <= quantity;i++){ //for each item bought increment the price of the item based on the factor, i have to search a mathematical way of doing this FASTER
					items[name].price[propertyName].quantity *= items[name].increment; 
					items[name].price[propertyName].quantity = Math.floor(items[name].price[propertyName].quantity);
				}
				
				
		}
		items[name].quantity += quantity; //add the boughts items
		
		for(i=1;i <= quantity;i++){ //for each item bought increment the price of the item based on the factor, i have to search a mathematical way of doing this FASTER
			//items[name].price *= items[name].increment; 
			//items[name].price = Math.floor(items[name].price);
		}
		items[name].updateHtml();
		
	}
	setTimeout(function(){ init();}, 5000);
